version: 2.1

orbs:
  common: radar/common@1.0
  node: radar/node@1.0

run_tests: &run_tests
  machine: true
  working_directory: ~/project
  steps:
  - checkout
  - common/install-docker-compose
  - node/install:
      node-version: $NODE_VERSION
  - run:
      name: Setup Integration Environment
      command: |
        source ~/.bashrc
        scripts/simnet-setup.sh ci
  - run:
      name: Setup Environment Variables
      command: cp .env.test .env
  - run: 
      name: Run Tests
      command: |
        source ~/.bashrc
        yarn test

jobs:
  test-node-8:
    environment:
      NODE_VERSION: 8
    <<: *run_tests
  test-node-10:
    environment:
      NODE_VERSION: 10
    <<: *run_tests
  test-node-11:
    environment:
      NODE_VERSION: 11
    <<: *run_tests

workflows:
  default:
    jobs:
      - node/install-modules
      - node/lint:
          requires:
          - node/install-modules
      - node/audit:
          requires:
          - node/install-modules
      - test-node-8
      - test-node-10
      - test-node-11
